### Enable deep sleep ###
# CONFIG_ZMK_SLEEP=y


### Increase BT Power (Increases range) ###
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y


### DEBOUNCING ####
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5


### Allow Displays ###
CONFIG_ZMK_DISPLAY=y


### Prospector Dongle Configs ###
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_LAYER_ROLLER_ALL_CAPS=y
# CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=y
# CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=120


### Enable custom status screen globally ###
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y


### Nice View Gem Configs ###
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=y
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=120
CONFIG_NICE_VIEW_GEM_ANIMATION=n
# CONFIG_NICE_VIEW_GEM_ANIMATION_FRAME=1
# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960
