### Set battery reporting ###
CONFIG_ZMK_BATTERY_REPORTING=y

### Enable/disable deep sleep ###
# Docs: https://zmk.dev/docs/features/low-power-states
CONFIG_ZMK_SLEEP=y

### Idle Sleep Timeout ###
# Default: 15min
# Set in 'ms'
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

### Idle Timeout ###
# Default: 30sec (30000)
# Set in 'ms'
CONFIG_ZMK_IDLE_TIMEOUT=30000

### Enable soft off ###
CONFIG_ZMK_PM_SOFT_OFF=y
