### Enable Mouse Feature ###
# Settings are set in .defconfig, but this is for exposure
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
# CONFIG_I2C=y
# CONFIG_INPUT_TPS43=y

### Set battery reporting ###
CONFIG_ZMK_BATTERY_REPORTING=y

### Enable/disable deep sleep ###
# Docs: https://zmk.dev/docs/features/low-power-states
CONFIG_ZMK_SLEEP=y

### Idle Sleep Timeout ###
# Default: 15min
# Set in 'ms'
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

### Idle Timeout ###
# Default: 30sec (30000)
# Set in 'ms'
CONFIG_ZMK_IDLE_TIMEOUT=30000

### Stack Memory Size ###
# Zephyr Default: 512 bytes
# BeeKeeb Default: 2048 bytes
CONFIG_INPUT_THREAD_STACK_SIZE=2048

### Enable soft off ###
CONFIG_ZMK_PM_SOFT_OFF=y
