### Enable Mouse Feature ###
# Settings are set in .defconfig, but this is for exposure
CONFIG_ZMK_MOUSE=y

### Enable/disable deep sleep ###
# Docs: https://zmk.dev/docs/features/low-power-states
CONFIG_ZMK_SLEEP=y

### Stack Memory Size ###
# Zephyr Default: 512 bytes
# BeeKeeb Default: 2048 bytes
CONFIG_INPUT_THREAD_STACK_SIZE=2048
